//
//  RetryViewControllerTests.swift
//  CleanSwift
//
//  Created by Raheel Sadiq on 30/11/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwift
import XCTest

class RetryViewControllerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: RetryViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupRetryViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupRetryViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "RetryViewController") as! RetryViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testRetryAction() {
        // Given
        var retryCalled = false
        sut.retryCalled = {
            retryCalled = true
        }
        
        // When
        loadView()
        sut.retryAction()
        
        // Then
        XCTAssertTrue(retryCalled, "Closure not called")
    }
}
